# Generated by Django 5.1.6 on 2025-09-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_alter_moviesmanager_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="moviesmanager",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="moviesmanager",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
